version: 1.0.{build}
os: Visual Studio 2015
image: Visual Studio 2015
branches:
  except:
  - develop/*
configuration: Release
install:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/install-nuget-3-3-0.ps1'))
cache: '%USERPROFILE%\.nuget\packages -> **\project.json'
nuget:
  account_feed: true
  project_feed: true
before_build:
- ps: nuget restore src -Verbosity quiet
build_script:
- ps: build.ps1
artifacts:
- path: bin\**\*.nupkg
  name: NuGet Package