version: 1.0.{build}
branches:
  except:
  - develop/*
skip_tags: true
configuration: Release
nuget:
  account_feed: true
  project_feed: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal